---
# tasks file for install_nginx

- name: install latest epel-release
  yum:
    name: epel-release
    state: latest

- name: install nginx
  yum:
    name: nginx
    state: present

- name: start and enable nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: copy nginx.conf template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: clear contents of /usr/share/nginx/html/ folder
  file:
    path: /usr/share/nginx/html/
    state: absent

- name: copy index.html file
  file:
    src: index.html
    dest: /usr/share/nginx/html/index.html
  notify: restart nginx