---
# tasks file for setup_nginx

- name: install nginx
  yum:
    name: nginx
    state: present

- name: start and enable nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: make a ssl folder
  file:
    path: "{{ ssl_directory }}"
    state: directory

- name: create self-signed SSL cert
  command: "{{ ssl_command }}"
  notify: restart nginx

- name: update nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: clear contents of /usr/share/nginx/html/ folder
  command: rm -rf /usr/share/nginx/html/*

- name: copy index.html file
  file:
    src: $HOME/SRE_Challenge/index.html
    dest: "{{ index_location }}"
  notify: restart nginx

