
---
- name: geerlingguy.java
  src: https://github.com/geerlingguy/ansible-role-java.git
  version: 1.9.1
- name: rvm_io.ruby
  src: https://github.com/rvm/rvm1-ansible.git
  version: v2.0.1
- name: geerlingguy.nodejs
  src: https://github.com/geerlingguy/ansible-role-nodejs.git
  version: 4.2.2